# Generated by Django 3.0.4 on 2020-04-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200424_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='losts',
            new_name='lost',
        ),
    ]
