# Generated by Django 3.0.4 on 2020-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200425_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
